### ISSUE TITLE
New dashboard columns (HOME & VISITOR)

### ISSUE THREAD

**Issue by Ian-Inizias** [Ian-Liceranzu/BasketLeague2#15]
**Is your feature request related to a problem? Please describe.**
Add two new columns to make leaderboard more similar to the the google example.

**Describe the solution you'd like**
Add two new columns called HOME and VISITOR showing the wins and loses in each case.

![image](https://github.com/Ian-Liceranzu/BasketLeague2/assets/43787552/cf53a783-474a-4962-820d-e05e535dab7c)

**Comment by Ian-Liceranzu** [comment]
Closed in #16
